/**
 * Tests for `generatedMarker`, the shared do-not-edit comment both
 * `generate-contract-addresses.mjs` and `generate-precompile-tables.mjs` prepend to what they
 * write. Pinned here so the two generators cannot drift in wording (FS-2728), and so a change
 * to the shape is a deliberate, reviewed edit rather than something that slips in unnoticed.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';

import { generatedMarker } from './generated-partial.mjs';

const PRECOMPILE_DIR = path.join('content', 'partials', 'precompile-tables');

/**
 * The shape every generated precompile partial's first line must have. The command is pinned, not a
 * generic backtick group, so a marker rewritten to name some other generator fails here.
 */
const MARKER_SHAPE =
  /^\{\/\* AUTOGENERATED\. Do not edit by hand\. Run `pnpm precompiles:generate` after .+\. \*\/\}$/;

/**
 * Fifteen precompiles plus `_NodeInterface.mdx`. Pinned so a partial going missing fails here
 * rather than shrinking the suite; adding a precompile is a deliberate edit to this number.
 */
const EXPECTED_PRECOMPILE_PARTIALS = 16;

describe('generatedMarker', () => {
  it('renders an MDX comment naming the regenerate command and the trigger', () => {
    assert.equal(
      generatedMarker('pnpm contracts:generate', 'bumping @arbitrum/sdk'),
      '{/* AUTOGENERATED. Do not edit by hand. Run `pnpm contracts:generate` after bumping @arbitrum/sdk. */}',
    );
  });

  it('rejects an argument containing `*/`, which would close the comment early', () => {
    // Left unchecked the marker would end at the caller's `*/` and leak its own tail into the
    // page as body copy. The generator's own output would look fine and only the rendered page
    // would show it, which is why this throws rather than escaping.
    assert.throws(() => generatedMarker('pnpm x:generate', 'editing a */ file'), /may not contain/);
    assert.throws(() => generatedMarker('pnpm */ generate', 'editing x'), /may not contain/);
  });

  it('rejects an argument containing a newline, which would split the marker in two', () => {
    assert.throws(() => generatedMarker('pnpm a\nb', 'c'), /may not contain a newline/);
    assert.throws(
      () => generatedMarker('pnpm x:generate', 'editing\nx'),
      /may not contain a newline/,
    );
  });

  it('starts with "{" so partial-catalog summary derivation skips it like it skips <table>', () => {
    // scripts/lib/partials.mjs's deriveSummary skips lines starting with "{" or "<" while looking
    // for a partial's first sentence, so the marker must keep starting with "{" or every
    // generated partial's catalog summary would be the marker text. deriveTitle reaches the same
    // outcome by a different route: it inspects only the first non-blank line and falls back to
    // the humanized filename when that line is neither an ATX heading nor a VanillaAdmonition,
    // which is what `<table>` already did before the marker existed.
    assert.ok(generatedMarker('pnpm x:generate', 'editing x').startsWith('{'));
  });
});

/**
 * `generate-precompile-tables.mjs` cannot be imported for a unit test: it calls `runScript(main)`
 * at module scope and fetches every pinned source over the network, so its only end-to-end guard
 * is `precompiles:check`, which is network-bound and `continue-on-error` in CI. This asserts the
 * committed result instead, which is offline and blocking through `pnpm test`. It proves the
 * marker is on disk, not that the generator is what put it there.
 */
describe('generated precompile partials', () => {
  const files = fs.readdirSync(PRECOMPILE_DIR).filter((name) => name.endsWith('.mdx'));

  it(`finds all ${EXPECTED_PRECOMPILE_PARTIALS} partials`, () => {
    assert.equal(
      files.length,
      EXPECTED_PRECOMPILE_PARTIALS,
      `unexpected partial set in ${PRECOMPILE_DIR}`,
    );
  });

  for (const name of files) {
    it(`${name} opens with the do-not-edit marker`, () => {
      const [first, second] = fs.readFileSync(path.join(PRECOMPILE_DIR, name), 'utf-8').split('\n');
      assert.match(first, MARKER_SHAPE);
      assert.equal(second, '', 'the marker must be followed by a blank line');
    });
  }
});
