/**
 * Tests for `generatedMarker`, the shared do-not-edit comment both
 * `generate-contract-addresses.mjs` and `generate-precompile-tables.mjs` prepend to what they
 * write. Pinned here so the two generators cannot drift in wording (FS-2728), and so a change
 * to the shape is a deliberate, reviewed edit rather than something that slips in unnoticed.
 */
import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { generatedMarker } from './generated-partial.mjs';

describe('generatedMarker', () => {
  it('renders an MDX comment naming the regenerate command and the trigger', () => {
    assert.equal(
      generatedMarker('pnpm contracts:generate', 'bumping @arbitrum/sdk'),
      '{/* AUTOGENERATED. Do not edit by hand. Run `pnpm contracts:generate` after bumping @arbitrum/sdk. */}',
    );
  });

  it('is a single line with no embedded newline, so it survives as one MDX comment', () => {
    const marker = generatedMarker('pnpm precompiles:generate', 'bumping nitroVersionTag');
    assert.ok(!marker.includes('\n'));
  });

  it('never emits a literal `*/` before its own closing delimiter', () => {
    // A trigger or command string containing `*/` would prematurely close the MDX comment and
    // leak the rest of the marker as page content. Nothing in this repo's inputs does that
    // today, but the check documents the constraint for the next caller.
    const marker = generatedMarker('pnpm x:generate', 'editing scripts/data/x.mjs');
    const withoutClosingDelimiter = marker.slice(2, -2);
    assert.ok(!withoutClosingDelimiter.includes('*/'));
  });

  it('starts with "{" so partial-catalog title/summary derivation skips it like it skips <table>', () => {
    // scripts/lib/partials.mjs's deriveTitle/deriveSummary skip lines starting with "{" or "<"
    // when looking for a partial's title or first sentence. The marker must keep starting with
    // "{" or every generated partial's catalog entry would show the marker text instead of its
    // real title/summary.
    assert.ok(generatedMarker('pnpm x:generate', 'editing x').startsWith('{'));
  });
});
