/**
 * Tests for the Stylus-by-Example page transform.
 *
 * The fixture is a miniature `page.mdx` written inline, not a copy of an upstream example, so a
 * regression shows up as a named failing case rather than as a diff in nineteen generated pages
 * nobody reads line by line. Nothing here imports the runner, which would drag a network clone
 * and a repo-root cwd into the suite; the runner is wiring over the functions tested below.
 *
 * The data file is asserted against the committed tree instead: the allowlist doubles as the
 * `meta.json` order, so an entry that rots into a page nobody publishes would otherwise only
 * surface as a failed weekly refresh.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';

import { outputDir, sections } from './data/stylus-examples.data.mjs';
import {
  buildPage,
  buildSectionMeta,
  insertNotForProductionBanner,
  parseMetadata,
  renderFrontmatter,
  rewriteRelativeLinks,
  yamlScalar,
} from './lib/stylus-examples.mjs';

const SOURCE = `export const metadata = {
  title: 'Hello World • Stylus by Example',
  description:
    'Prints output to the terminal using the \`console!\` macro.',
};

{/* Begin Content */}

# Hello World

Prose before the snippet, and a link to [ABI Encode](./abi_encode).

### Examples

\`\`\`rust
console!("hello there!");
\`\`\`
`;

const SECTIONS = [
  { dir: 'basic_examples', pages: ['abi_encode', 'hello_world'] },
  { dir: 'applications', pages: ['erc20'] },
];

const DEFAULTS = { content_type: 'concept', author: 'gblanchemain', sme: 'gblanchemain' };
const INCLUDE = '<include cwd>content/partials/_not-for-production-banner-partial.mdx</include>';

const build = (source = SOURCE) =>
  buildPage({
    source,
    context: 'src/app/basic_examples/hello_world/page.mdx',
    marker: '{/* AUTOGENERATED. */}',
    frontmatterDefaults: DEFAULTS,
    sections: SECTIONS,
    baseUrl: '/docs/stylus/stylus-by-example',
    include: INCLUDE,
  });

describe('parseMetadata', () => {
  it('reads the title and description off the Next.js metadata export', () => {
    const metadata = parseMetadata(SOURCE, 'fixture');
    assert.equal(metadata.title, 'Hello World • Stylus by Example');
    assert.match(metadata.description, /^Prints output to the terminal/);
  });

  it('throws when the page has no metadata export', () => {
    assert.throws(
      () => parseMetadata('# Just a heading\n', 'fixture'),
      /no `export const metadata`/,
    );
  });

  it('throws when a required field is missing, rather than emitting empty frontmatter', () => {
    // An empty `description` passes YAML and fails the Zod schema in source.config.ts, which
    // would surface as a build error on a page this generator wrote, far from the cause.
    const source = `export const metadata = { title: 'T' };\n`;
    assert.throws(() => parseMetadata(source, 'fixture'), /metadata\.description is missing/);
  });
});

describe('yamlScalar', () => {
  it('single-quotes a plain value', () => {
    assert.equal(yamlScalar('Hello World'), "'Hello World'");
  });

  it('doubles an apostrophe so the scalar stays valid YAML', () => {
    assert.equal(yamlScalar("Arbitrum's SDK"), "'Arbitrum''s SDK'");
  });
});

describe('renderFrontmatter', () => {
  const block = renderFrontmatter({ title: 'T', description: 'D' }, DEFAULTS);

  it('emits the five fields this repo requires, in the committed order', () => {
    assert.deepEqual(block.split('\n'), [
      '---',
      "title: 'T'",
      "description: 'D'",
      "content_type: 'concept'",
      'author: gblanchemain',
      'sme: gblanchemain',
      '---',
    ]);
  });
});

describe('rewriteRelativeLinks', () => {
  const options = {
    sections: SECTIONS,
    baseUrl: '/docs/stylus/stylus-by-example',
    context: 'fixture',
  };

  it('resolves a same-directory link against the section that publishes the slug', () => {
    assert.equal(
      rewriteRelativeLinks('See [ABI Encode](./abi_encode).', options),
      'See [ABI Encode](/docs/stylus/stylus-by-example/basic_examples/abi_encode).',
    );
  });

  it('resolves against the owning section, not a hardcoded one', () => {
    // Upstream's version of this rule hardcodes `basic_examples`, which is only ever right
    // because the one relative link in the published set happens to live there.
    assert.equal(
      rewriteRelativeLinks('See [ERC-20](./erc20).', options),
      'See [ERC-20](/docs/stylus/stylus-by-example/applications/erc20).',
    );
  });

  it('leaves an absolute link alone', () => {
    const link = 'See [the docs](https://docs.arbitrum.io/stylus).';
    assert.equal(rewriteRelativeLinks(link, options), link);
  });

  it('throws on a link to an example this site does not publish', () => {
    // Otherwise it ships as a 404 that only check-links catches, after the page is committed.
    assert.throws(
      () => rewriteRelativeLinks('See [Arrays](./arrays).', options),
      /this site does not publish/,
    );
  });
});

describe('insertNotForProductionBanner', () => {
  it('lands the banner above the first Rust fence, under the heading that introduces it', () => {
    const { content, inserted } = insertNotForProductionBanner(
      '### Examples\n\n```rust\nfn main() {}\n```\n',
      INCLUDE,
    );
    assert.equal(inserted, true);
    const lines = content.split('\n').filter((line) => line !== '');
    assert.deepEqual(lines.slice(0, 3), ['### Examples', INCLUDE, '```rust']);
  });

  it('inserts once, ahead of the first fence only', () => {
    const { content } = insertNotForProductionBanner(
      '# T\n\n```rust\na\n```\n\n## More\n\n```rust\nb\n```\n',
      INCLUDE,
    );
    assert.equal(content.split(INCLUDE).length - 1, 1);
  });

  it('reports rather than throws when the page has no Rust snippet', () => {
    const { content, inserted } = insertNotForProductionBanner(
      '# T\n\n```toml\na = 1\n```\n',
      INCLUDE,
    );
    assert.equal(inserted, false);
    assert.equal(content, '# T\n\n```toml\na = 1\n```\n');
  });
});

describe('buildPage', () => {
  const { content, metadata, banner } = build();

  it('replaces the metadata export with frontmatter and the do-not-edit marker', () => {
    assert.match(content, /^---\ntitle: 'Hello World • Stylus by Example'\n/);
    assert.match(content, /---\n\n\{\/\* AUTOGENERATED\. \*\/\}\n/);
    assert.doesNotMatch(content, /export const metadata/);
  });

  it("keeps upstream's Begin Content marker where upstream put it", () => {
    assert.match(content, /\{\/\* AUTOGENERATED\. \*\/\}\n\n\{\/\* Begin Content \*\/\}\n/);
  });

  it('rewrites the relative link and inserts the banner', () => {
    assert.match(content, /\(\/docs\/stylus\/stylus-by-example\/basic_examples\/abi_encode\)/);
    assert.ok(content.includes(INCLUDE));
    assert.equal(banner, true);
  });

  it('hands back the parsed metadata, so the runner can report on it', () => {
    assert.equal(metadata.title, 'Hello World • Stylus by Example');
  });

  it('leaves the body below the banner untouched', () => {
    assert.match(content, /```rust\nconsole!\("hello there!"\);\n```/);
  });
});

describe('buildSectionMeta', () => {
  it('keeps the listed order and appends the catch-all the committed files carry', () => {
    assert.deepEqual(buildSectionMeta({ title: 'Applications', pages: ['erc20', 'erc721'] }), {
      title: 'Applications',
      pages: ['erc20', 'erc721', '...'],
    });
  });
});

describe('stylus-examples.data.mjs', () => {
  it('names a page that exists for every allowlist entry', () => {
    for (const section of sections) {
      for (const slug of section.pages) {
        const file = path.join(outputDir, section.dir, `${slug}.mdx`);
        assert.ok(fs.existsSync(file), `${file} is listed in the data file but does not exist`);
      }
    }
  });

  it('lists every committed page, so none is left unmanaged by the generator', () => {
    for (const section of sections) {
      const dir = path.join(outputDir, section.dir);
      const committed = fs
        .readdirSync(dir)
        .filter((name) => name.endsWith('.mdx'))
        .map((name) => name.replace(/\.mdx$/, ''));
      assert.deepEqual([...committed].sort(), [...section.pages].sort());
    }
  });

  it('matches the committed meta.json, which is what fixes the sidebar order', () => {
    for (const section of sections) {
      const meta = JSON.parse(fs.readFileSync(path.join(outputDir, section.dir, 'meta.json')));
      assert.deepEqual(meta, buildSectionMeta(section));
    }
  });
});
